### ISSUE TITLE
AcuFile plot_power_spectrum() raises exception

### ISSUE THREAD

**Issue by carueda** [lifewatch/pypam#5]
We just started having a closer look at PyPam and found that plot related functions are failing with a `KeyError` exception, e.g., a stack trace when calling AcuFile's `plot_power_spectrum()` is enclosed below.  

We put together a small repo (with a small wav file) to facilitate reproduction of the problem:  https://github.com/mbari-org/pypam-test

We initially encountered this problem on a macOS with python 3.9 (where all required packages apparently were [installed successfully](https://github.com/mbari-org/pypam-test/blob/main/pip-install-output.txt)), but then also reproduced it on a Linux system (which is a usual working environment for us).

Thanks for your attention.

---

```
Traceback (most recent call last):
  File ".../pypam-test/repro.py", line 8, in <module>
    acu_file.plot_power_spectrum()
  File ".../pypam-test/virtenv/lib/python3.9/site-packages/pypam/acoustic_file.py", line 1055, in plot_power_spectrum
    self._plot_spectrum(ds=power, col_name='spectrum', units=units,
  File ".../pypam-test/virtenv/lib/python3.9/site-packages/pypam/acoustic_file.py", line 1060, in _plot_spectrum
    plots.plot_spectrum(ds, 'band_' + col_name, log=log, ylabel=units, save_path=save_path)
  File ".../pypam-test/virtenv/lib/python3.9/site-packages/pypam/plots.py", line 105, in plot_spectrum
    ds[col_name].sel(datetime=time_bin).plot.line(xscale=xscale)
  File ".../pypam-test/virtenv/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1523, in sel
    ds = self._to_temp_dataset().sel(
  File ".../pypam-test/virtenv/lib/python3.9/site-packages/xarray/core/dataset.py", line 2550, in sel
    query_results = map_index_queries(
  File ".../pypam-test/virtenv/lib/python3.9/site-packages/xarray/core/indexing.py", line 175, in map_index_queries
    grouped_indexers = group_indexers_by_index(obj, indexers, options)
  File ".../pypam-test/virtenv/lib/python3.9/site-packages/xarray/core/indexing.py", line 137, in group_indexers_by_index
    raise KeyError(f"no index found for coordinate {key!r}")
KeyError: "no index found for coordinate 'datetime'"
```

**Comment by cparcerisas** [comment]
Dear, 
Thanks for pointing out the issue. I solved it in the branch tests. I will soon release a new version with all the bugs solved and some new functionalities.

**Comment by carueda** [comment]
@cparcerisas Thanks much for looking into the issue!  If you think it is worthwhile, we would be be happy to try the mentioned tests branch while a proper release is available?  (cc @ryjombari)

**Comment by carueda** [comment]
Hi @cparcerisas I just tried the `tests` branch (commit 5f21f7e8 at this point) and getting what looks like basically the same issue.

To be more concrete, under a pypam clone with such a branch, along with a copy of the test wav file `ST600HF.220616210000.wav` included in https://github.com/mbari-org/pypam-test:

```
python3 -c "import pyhydrophone
from pypam.acoustic_file import AcuFile

st = pyhydrophone.SoundTrap('SoundTrap', 'ST600HF', '6716')

acu_file = AcuFile('ST600HF.220616210000.wav', st, 1)

acu_file.plot_power_spectrum()
"

Traceback (most recent call last):
  File "/Users/carueda/github/pypam/virtenv/lib/python3.9/site-packages/xarray/core/indexing.py", line 73, in group_indexers_by_index
    index = xindexes[key]
KeyError: 'datetime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "/Users/carueda/github/pypam/pypam/acoustic_file.py", line 1055, in plot_power_spectrum
    self._plot_spectrum(ds=power, col_name='spectrum', units=units,
  File "/Users/carueda/github/pypam/pypam/acoustic_file.py", line 1060, in _plot_spectrum
    plots.plot_spectrum(ds, 'band_' + col_name, log=log, ylabel=units, save_path=save_path)
  File "/Users/carueda/github/pypam/pypam/plots.py", line 106, in plot_spectrum
    ds[col_name].sel(datetime=time_bin).plot.line(xscale=xscale)
  File "/Users/carueda/github/pypam/virtenv/lib/python3.9/site-packages/xarray/core/dataarray.py", line 1329, in sel
    ds = self._to_temp_dataset().sel(
  File "/Users/carueda/github/pypam/virtenv/lib/python3.9/site-packages/xarray/core/dataset.py", line 2501, in sel
    pos_indexers, new_indexes = remap_label_indexers(
  File "/Users/carueda/github/pypam/virtenv/lib/python3.9/site-packages/xarray/core/coordinates.py", line 421, in remap_label_indexers
    pos_indexers, new_indexes = indexing.remap_label_indexers(
  File "/Users/carueda/github/pypam/virtenv/lib/python3.9/site-packages/xarray/core/indexing.py", line 110, in remap_label_indexers
    indexes, grouped_indexers = group_indexers_by_index(
  File "/Users/carueda/github/pypam/virtenv/lib/python3.9/site-packages/xarray/core/indexing.py", line 84, in group_indexers_by_index
    raise KeyError(f"no index found for coordinate {key}")
KeyError: 'no index found for coordinate datetime'
```

Does the above work for you?
